### ISSUE TITLE
VAT validation no longer works

### ISSUE THREAD

**Issue by tomkra** [gem-shards/europe.rb#1]
VAT validation stopped working correctly and raises an error. 

Try with example:

```
Europe::Vat.validate('NL009291477B01')
```

and got error `NoMethodError (undefined method "elements" for nil:NilClass)`.

Gem version: 0.0.18

**Comment by VvanGemert** [comment]
Hi @tomkra , You're right. I'm looking into it right now

**Comment by VvanGemert** [comment]
@tomkra It's fixed if you update to version 0.0.19. Thank you for notifying me!

**Comment by tomkra** [comment]
Thank you @VvanGemert , for super quick fix :)
