### ISSUE TITLE
service down - error handling. 

### ISSUE THREAD

**Issue by kpbacode** [gem-shards/europe.rb#2]
europe-0.0.19/lib/europe/vat/rates.rb:25:in `extract_rates': undefined method `first' for nil:NilClass (NoMethodError)
        data = resp.scan(%r{\\<tbody\\>(.*)\\<\\/tbody\\>}m).first.first.strip
                                                             ^^^^^^
![Screenshot 2022-10-29 at 13 19 16](https://user-images.githubusercontent.com/65641209/198828539-7130accc-7f50-446e-956a-909bfd9eb31e.png)

**Comment by VvanGemert** [comment]
Hi @kpbacode , Thank you for reporting this issue. I've fixed this in version 0.0.20. I've added hard coded fallback rates which are returned when the request fails or the data isn't present on the EU website.
